export const GENERAL_SET_CATEGORY = 'GENERAL_SET_CATEGORY'
export const GENERAL_TOGGLE_MENU = 'GENERAL_TOGGLE_MENU'
export const GENERAL_SET_PRODUCT = 'GENERAL_SET_PRODUCT'
export const GENERAL_TOGGLE_PRODUCT = 'GENERAL_TOGGLE_PRODUCT'